ICIP:
  train_all_item:
    batch_size: 128
    epochs: 30
    early_stop_turns: 5
    early_stop_min_delta: 1e-3
    lr: 1e-4
    retrieval_num: 50
  train_single_item:
    batch_size: 1024
    epochs: 30
    early_stop_turns: 5
    early_stop_min_delta: 1e-3
    lr: 5e-6
    retrieval_num: 1
  train:
    batch_size: 64
    early_stop_turns: 5
    lr: 1e-4
    retrieval_num: 50
  

SMPD:
  train_all_item:
    batch_size: 64
    epochs: 30
    early_stop_turns: 5
    early_stop_min_delta: 1e-3
    lr: 1e-5
    retrieval_num: 50
  train_single_item:
    batch_size: 256
    epochs: 30
    early_stop_turns: 5
    early_stop_min_delta: 1e-3
    lr: 1e-5
    retrieval_num: 1
  train:
    batch_size: 64
    early_stop_turns: 5
    lr: 1e-4
    retrieval_num: 50

Instagram:
  train_all_item:
    batch_size: 64
    epochs: 30
    early_stop_turns: 5
    early_stop_min_delta: 1e-3
    lr: 1e-4
    retrieval_num: 50
  train_single_item:
    batch_size: 256
    epochs: 30
    early_stop_turns: 5
    early_stop_min_delta: 1e-3
    lr: 1e-4
    retrieval_num: 1
  train:
    batch_size: 64
    early_stop_turns: 5
    lr: 1e-4
    retrieval_num: 50
